/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlAgendarCitaMedica;
import dto.HorarioCitaDTO;
import dto.HorarioConsultaDTO;
import dto.MedicoConCitasDTO;
import dto.MedicoDTO;
import java.awt.CardLayout;
import java.time.DayOfWeek;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rocha
 */
public class FrameRegistrarCita extends javax.swing.JFrame {

    private MediadorFlujo mediador;
    DefaultTableModel tblModelMedicos;
    DefaultTableModel tblModelCitas;

    /**
     * Creates new form FrameBusquedaPaciente
     */
    public FrameRegistrarCita() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        
        panelInfo.setVisible(false);
        
        mediador = MediadorFlujo.getInstance();
        
        configurarTablas();
        configurarListeners();
        cargarMedicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panelSelecionarMedico = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicos = new javax.swing.JTable();
        panelSeleccionarCita = new javax.swing.JPanel();
        panelSinCitas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelCitas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        panelInfoMedico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblEspecialidadMedico = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblConsultorioMedico = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblCedulaMedico = new javax.swing.JLabel();
        panelHorarioMedico = new javax.swing.JPanel();
        panelInfoCita = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Registrar cita médica");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("3. Seleccionar médico");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("4. Seleccionar cita");

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Lista de médicos");

        panelSelecionarMedico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Seleccione un médico haciendo click en la fila.");

        tblMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMedicos.getTableHeader().setResizingAllowed(false);
        tblMedicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMedicos);

        javax.swing.GroupLayout panelSelecionarMedicoLayout = new javax.swing.GroupLayout(panelSelecionarMedico);
        panelSelecionarMedico.setLayout(panelSelecionarMedicoLayout);
        panelSelecionarMedicoLayout.setHorizontalGroup(
            panelSelecionarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecionarMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelecionarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSelecionarMedicoLayout.setVerticalGroup(
            panelSelecionarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecionarMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSeleccionarCita.setLayout(new java.awt.CardLayout());

        panelSinCitas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel14.setText("Es necesario seleccionar un médico primero");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("No hay citas para mostrar");

        javax.swing.GroupLayout panelSinCitasLayout = new javax.swing.GroupLayout(panelSinCitas);
        panelSinCitas.setLayout(panelSinCitasLayout);
        panelSinCitasLayout.setHorizontalGroup(
            panelSinCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSinCitasLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(19, 19, 19))
            .addGroup(panelSinCitasLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSinCitasLayout.setVerticalGroup(
            panelSinCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinCitasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        panelSeleccionarCita.add(panelSinCitas, "NOCITAS");

        panelCitas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Seleccione una cita haciendo click en la fila.");

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tblCitas);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Citas disponibles");

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar cita");
        btnRegistrar.setEnabled(false);

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelSeleccionarCita.add(panelCitas, "CITAS");

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setLayout(new java.awt.CardLayout());

        panelInfoMedico.setBackground(new java.awt.Color(245, 245, 220));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre completo");

        lblNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreMedico.setText("Aa");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Especialidad");

        lblEspecialidadMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEspecialidadMedico.setText("Aa");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("N. cédula profesional");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Consultorio");

        lblConsultorioMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConsultorioMedico.setText("Aa");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Datos del médico seleccionado");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Días y horas de consulta");

        lblCedulaMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedulaMedico.setText("Aa");

        panelHorarioMedico.setBackground(new java.awt.Color(245, 245, 220));
        panelHorarioMedico.setLayout(new javax.swing.BoxLayout(panelHorarioMedico, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout panelInfoMedicoLayout = new javax.swing.GroupLayout(panelInfoMedico);
        panelInfoMedico.setLayout(panelInfoMedicoLayout);
        panelInfoMedicoLayout.setHorizontalGroup(
            panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoMedicoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(panelInfoMedicoLayout.createSequentialGroup()
                        .addGroup(panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblNombreMedico)
                            .addComponent(jLabel10)
                            .addComponent(lblEspecialidadMedico)
                            .addComponent(jLabel12)
                            .addComponent(lblCedulaMedico)
                            .addComponent(jLabel18))
                        .addGap(27, 27, 27)
                        .addGroup(panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelHorarioMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addGroup(panelInfoMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultorioMedico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoMedicoLayout.setVerticalGroup(
            panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoMedicoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoMedicoLayout.createSequentialGroup()
                        .addComponent(lblNombreMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEspecialidadMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCedulaMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConsultorioMedico))
                    .addComponent(panelHorarioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        panelInfo.add(panelInfoMedico, "MEDICO");

        panelInfoCita.setBackground(new java.awt.Color(245, 245, 220));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Nombre del paciente");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Aa");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("CURP del paciente");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Aa");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("NSS del paciente");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Consultorio");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Aa");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Detalles de la cita");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Nombre del médico");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Aa");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Aa");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Aa");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Fecha y hora");

        javax.swing.GroupLayout panelInfoCitaLayout = new javax.swing.GroupLayout(panelInfoCita);
        panelInfoCita.setLayout(panelInfoCitaLayout);
        panelInfoCitaLayout.setHorizontalGroup(
            panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoCitaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(panelInfoCitaLayout.createSequentialGroup()
                        .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel34))
                        .addGap(49, 49, 49)
                        .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel35)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel28))))
                .addGap(19, 19, 19))
        );
        panelInfoCitaLayout.setVerticalGroup(
            panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoCitaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel29))
                .addGap(96, 96, 96))
        );

        panelInfo.add(panelInfoCita, "CITA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(panelSelecionarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel13))
                                .addComponent(panelSeleccionarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(498, 498, 498))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSelecionarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSeleccionarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        volver();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void configurarTablas() {
        tblModelMedicos = new DefaultTableModel(new Object[]{"N. cédula profesional", "Nombre"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda es editable
            }
        };

        tblMedicos.setModel(tblModelMedicos);

        tblModelCitas = new DefaultTableModel(new Object[]{"Fecha", "Hora"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda es editable
            }
        };
        
        tblCitas.setModel(tblModelCitas);
    }

    private void configurarListeners() {
        tblMedicos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                actualizarCitas();
                panelInfo.setVisible(tblMedicos.getSelectedRow() != -1);
            }
        });

        tblCitas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                // Si hay fila seleccionada (>=0), habilitar el botón
                btnRegistrar.setEnabled(tblCitas.getSelectedRow() != -1);
            }
        });

    }
    
    private void cargarMedicos() {
        List<MedicoDTO> medicos = obtenerMedicos();

        // Limpiar cualquier fila existente
        tblModelMedicos.setRowCount(0);

        // Agregar cada médico como fila
        for (MedicoDTO medico : medicos) {
            tblModelMedicos.addRow(new Object[]{
                medico.getCedula(),
                medico.getNombreCompleto()
            });
        }
    }

    private List<MedicoDTO> obtenerMedicos() {
        return ControlAgendarCitaMedica.obtenerMedicos();
    }
    
    private void actualizarCitas() {
        tblModelCitas.setRowCount(0);
        btnRegistrar.setEnabled(false);
        
        CardLayout cl = (CardLayout) panelSeleccionarCita.getLayout();
        MedicoConCitasDTO medicoConCitas = obtenerCitas();
        List<HorarioCitaDTO> citas = medicoConCitas.getCitasDisponibles();
        
        if (citas.isEmpty()) {
            cl.show(panelSeleccionarCita, "NOCITAS");
            return;
        }
        
        for (HorarioCitaDTO horario: medicoConCitas.getCitasDisponibles()) {
            tblModelCitas.addRow(new Object[]{
                horario.getFecha(),
                horario.getHora()
            });
        }
        
        
        cl.show(panelSeleccionarCita, "CITAS");
        
        mostrarInfoMedico(medicoConCitas.getMedico());
        
    }
    
    private void mostrarInfoMedico(MedicoDTO medico) {
        CardLayout cl = (CardLayout) panelInfo.getLayout();
        
        lblNombreMedico.setText(medico.getNombreCompleto());
        lblEspecialidadMedico.setText(medico.getEspecialidad());
        lblCedulaMedico.setText(medico.getCedula());
        lblConsultorioMedico.setText(medico.getConsultorio());
        
        
        mostrarHorario(medico.getHorarios());

        cl.show(panelInfo, "MEDICO");
    }

    private void mostrarHorario(List<HorarioConsultaDTO> horarios) {
        panelHorarioMedico.removeAll(); // limpiar antes de cargar
        panelHorarioMedico.setLayout(new BoxLayout(panelHorarioMedico, BoxLayout.Y_AXIS));

        Map<DayOfWeek, String> diasEsp = new HashMap<>();
        diasEsp.put(DayOfWeek.MONDAY, "Lunes");
        diasEsp.put(DayOfWeek.TUESDAY, "Martes");
        diasEsp.put(DayOfWeek.WEDNESDAY, "Miércoles");
        diasEsp.put(DayOfWeek.THURSDAY, "Jueves");
        diasEsp.put(DayOfWeek.FRIDAY, "Viernes");
        diasEsp.put(DayOfWeek.SATURDAY, "Sábado");
        diasEsp.put(DayOfWeek.SUNDAY, "Domingo");

        Map<DayOfWeek, HorarioConsultaDTO> horarioMedico = horarios.stream()
                .collect(Collectors.toMap(HorarioConsultaDTO::getDia, h -> h));
        
        // Recorremos de lunes a domingo
        for (DayOfWeek dia : DayOfWeek.values()) {
            if (horarioMedico.containsKey(dia)) {
                HorarioConsultaDTO horario = horarioMedico.get(dia);
                String texto = diasEsp.get(dia) + ": " + horario.getHoraInicio() + " a " + horario.getHoraFin();
                JLabel label = new JLabel(texto);
                panelHorarioMedico.add(label);
            }
        }

        panelHorarioMedico.revalidate();
        panelHorarioMedico.repaint();
    }


    private MedicoConCitasDTO obtenerCitas() {
        int fila = tblMedicos.getSelectedRow();
        
        String cedula = (String) tblModelMedicos.getValueAt(fila, 0);
        
        return ControlAgendarCitaMedica.obtenerMedico(cedula);
    }
    
    private void volver() {
        this.dispose();
        mediador.abrirBusquedaPacienteFrm();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCedulaMedico;
    private javax.swing.JLabel lblConsultorioMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JPanel panelHorarioMedico;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInfoCita;
    private javax.swing.JPanel panelInfoMedico;
    private javax.swing.JPanel panelSeleccionarCita;
    private javax.swing.JPanel panelSelecionarMedico;
    private javax.swing.JPanel panelSinCitas;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTable tblMedicos;
    // End of variables declaration//GEN-END:variables
}
